### PR TITLE
Clean up list

### PR DESCRIPTION
**Pull request by lynn**
Remove duplicates, lowercase everything, remove some words that are not adjectives (e.g. "handsomely", "two"), or that cannot be used attributively (e.g. "awake", "kaput").

I also removed "ugly", "stupid"... to prevent apps using these adjectives (for names or examples) from randomly insulting the user :)

### CODE REVIEW

**Comment by rgbkrk** [comment]
Oh my gosh! Thank you!

**Comment by rgbkrk** [comment]
I've added you to the repository as a collaborator if you're up for it. Not that there's any activity here, I just like sharing responsibility with kind helpful people. 😄 

I'll push out a release of this package when I get a chance later today.

**Comment by rgbkrk** [comment]
Shipped as `v1.0.2`

**Comment by lynn** [comment]
Thank you! :yellow_heart:

**Comment by parrotgeek1** [comment]
You missed some numbers like ten

**Pull request merged**
